name: Angular => Build, Test, Sonarcloud and deploy to docker

on: [push]

jobs:

  front-end-ci:
    name: App Hospital frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'app'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies with npm
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run Build
        run: npm run build

    