name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'api'
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
   
    - name: Compile with Maven
      run: mvn clean compile --file pom.xml
      
    - name: Run verify with maven
      run: mvn verify
      
    - name: Run package with maven
      run : mvn -B package -DskipTests --file pom.xml
